# Basic functions 

In [1]:
A = 5
B = "This is my first lecture"
print (A)
print (B)

5
This is my first lecture


In [3]:
c = (A == 10)
print (c)

False


In [4]:
D = A + 9   #+,-,/,* follows similarly
print (D)  
E = 10
D = A + E
print(D)

14
15


In [ ]:
D = A + B
print (D)

In [10]:
A = 7

In [12]:
R = D % A
print (R)

7

In [3]:
A = [10]
B = A
A = A.append(5)
print(B)

[10, 5]


# Data types - Primitives

## Integer

In [15]:
A = 5    # A = int(5)
print(type(A))

<class 'int'>


In [16]:
B = 15
addition = A+B
print (type(addition))

<class 'int'>


## Float

In [17]:
A = 5.2  
print (type (A))

<class 'float'>


In [18]:
B = int (A)    # +, - ,*, / of floats will be floats 
print (B)
print (type(B))     

5
<class 'int'>


## String 

In [19]:
X = "Hello"
Y = "Students"
print (X)
print (X + Y)
print (type(X))

Hello
HelloStudents
<class 'str'>


In [20]:
print (X + " " + Y)

Hello Students


In [21]:
len(X)

5

In [22]:
U = "CRICKET"
print(U.lower()) 

cricket


In [ ]:
U.count(C)  
U.count("c") 
U.count("C")

In [30]:
A = "q"
print (type(A))

<class 'str'>


In [31]:
A.isdigit()

False

In [32]:
sample = "This is my first class"
len(sample)

22

In [36]:
words = sample.split()
print (words)

['This', 'is', 'my', 'first', 'class']


In [37]:
len(words)

5

## Boolean

In [ ]:
#Takes two values True(1) or false (0)

In [40]:
A = 3
B = "3"
C = (A == int(B))
print (C)

True


In [41]:
C + 10

11

# Data types - Non Primitives

## Array

In [42]:
import numpy as np

In [53]:
A = np.array([2,3,8])
print(A)

[2 3 8]


In [55]:
print(A[1])

3


In [49]:
A[2] = A[2] + 5
print (A)

[ 2  3 13]


In [50]:
print(len(A))
print(A.max())
print(A.min())
print(A.mean())
print(A.argmin())
print(A.sum())

3
13
2
6.0
0
18


In [62]:
B = np.array(([2,3,4],[1,5,9],[8,1,3]))

In [63]:
B

array([[2, 3, 4],
       [1, 5, 9],
       [8, 1, 3]])

In [64]:
print(B.shape)

(3, 3)


In [66]:
C = np.array(["a","b","q"])
C

array(['a', 'b', 'q'], dtype='<U1')

In [65]:
C = np.array(["a","b", 1])
C

array(['a', 'b', '1'], dtype='<U1')

In [68]:
C[2] = "t"
print(C)

['a' 'b' 't']


In [ ]:
C[3] = "10"

In [70]:
A = np.array([2,3,8])
D = np.array([5,8,9])
A+D

array([ 7, 11, 17])

## List

In [84]:
A = ["Python", "R", "Scala", "Java"]
A

['Python', 'R', 'Scala', 'Java']

In [73]:
A.append("MATLAB")
A

['Python', 'R', 'Scala', 'Java', 'MATLAB']

In [74]:
A.append(2)
A

['Python', 'R', 'Scala', 'Java', 'MATLAB', 2]

In [75]:
A[2] = "C++"
A

['Python', 'R', 'C++', 'Java', 'MATLAB', 2]

In [ ]:
A.pop()
A

In [86]:
B = ["India", "Canada", "USA"]

In [88]:
C = A+B
C

['Python', 'R', 'Scala', 'Java', 'India', 'Canada', 'USA']

In [91]:
C[2:len(C)] #2 to lend of the list

['Scala', 'Java', 'India', 'Canada', 'USA']

In [96]:
a = 10
A = [np.array([2,3]),5,a]

In [98]:
B

['India', 'Canada', 'USA']

In [ ]:
A

## Tuples

In [103]:
A = (2,4, "Python")
type(A)

tuple

In [ ]:
A[2] = "C++"

## Dictionary

In [ ]:
#key value pair??

In [107]:
population = {"TN":100, "MH": 120, "Kerala": 85, "Karnataka":20, "JK":"NA"}
population

{'TN': 100, 'MH': 120, 'Kerala': 85, 'Karnataka': 20, 'JK': 'NA'}

In [108]:
population["MH"]

120

In [109]:
population["JK"] =60
population

{'TN': 100, 'MH': 120, 'Kerala': 85, 'Karnataka': 20, 'JK': 60}

In [112]:
population.keys()

dict_keys(['TN', 'MH', 'Kerala', 'Karnataka', 'JK'])

In [113]:
population.values()

dict_values([100, 120, 85, 20, 60])

In [114]:
population.items()

dict_items([('TN', 100), ('MH', 120), ('Kerala', 85), ('Karnataka', 20), ('JK', 60)])

In [115]:
keys = ["Cricket", "Football", "Baseball"]
A = dict.fromkeys(keys)
A

{'Cricket': None, 'Football': None, 'Baseball': None}

In [116]:
A = dict.fromkeys(keys,0)
A

{'Cricket': 0, 'Football': 0, 'Baseball': 0}

## Sets

In [118]:
A =set((10,1,12, 10))
A

{1, 10, 12}

In [119]:
B = set ((1,2,3,4,5,1))
B

{1, 2, 3, 4, 5}

In [120]:
A.union(B)

{1, 2, 3, 4, 5, 10, 12}

In [121]:
A.intersection(B)

{1}

In [122]:
A.difference(B)

{10, 12}

In [123]:
A.isdisjoint(B)

False

In [124]:
A.issubset(B)

False

In [125]:
A =set((10,1,12)) 
B =set((10,1,12,5,6,7,8))

In [126]:
A.issubset(B)

True

In [127]:
B.issuperset(A)

True

## For loop

In [129]:
A = ["TN", "Kerala", "Karnataka", "Andaman", "Delhi","Himachal"]

In [130]:
for i in A:
    print ("Name of the state: " + i)

Name of the state: TN
Name of the state: Kerala
Name of the state: Karnataka
Name of the state: Andaman
Name of the state: Delhi
Name of the state: Himachal


In [131]:
for i in range(6):   #range(0,6)
    print (i)

0
1
2
3
4
5


# Exercise

In [ ]:
# Write a code to count the number of occurances of each word in a given sentence

In [133]:
sentence = "I am from chennai and I am working in Taramani"

In [135]:
set_of_words =set(words)
set_of_words

{'I', 'Taramani', 'am', 'and', 'chennai', 'from', 'in', 'working'}

In [ ]:
words = sentence.split()
set_of_words =set(words)

In [136]:
count = dict.fromkeys(set_of_words,0)

In [137]:
count

{'from': 0,
 'Taramani': 0,
 'working': 0,
 'in': 0,
 'and': 0,
 'am': 0,
 'I': 0,
 'chennai': 0}

In [138]:
for i in words:
     count[i] = count[i] + 1

In [139]:
count

{'from': 1,
 'Taramani': 1,
 'working': 1,
 'in': 1,
 'and': 1,
 'am': 2,
 'I': 2,
 'chennai': 1}