# Numpy and Pandas

In [9]:
import numpy as np

In [78]:
A = np.array([2,3,6,8])  ## np has a method called array which takes [numbers] and returns a object

In [79]:
print(A)

[2 3 6 8]


In [80]:
A*2

array([ 4,  6, 12, 16])

In [81]:
A**2

array([ 4,  9, 36, 64], dtype=int32)

In [85]:
np.sum(A)

19

In [83]:
np.median(A)

4.5

In [21]:
B = np.ones(4)
B

In [24]:
C = np.arange(5)
C

array([0, 1, 2, 3, 4])

In [69]:
A = np.array([[2,3],[-1,-2]])
A

array([[ 2,  3],
       [-1, -2]])

In [70]:
B = np.array([[3,-1],[0,2]])
B

array([[ 3, -1],
       [ 0,  2]])

In [71]:
A*B

array([[ 6, -3],
       [ 0, -4]])

In [72]:
A.dot(B)

array([[ 6,  4],
       [-3, -3]])

In [73]:
A.sum(axis=0)

array([1, 1])

In [74]:
np.random.randint(5,10,2)

array([8, 9])

In [75]:
np.random.uniform(5,10,2)

array([8.87115064, 5.85813887])

In [76]:
np.random.normal(2,1,5)

array([0.71944437, 1.77443237, 2.52801329, 2.45440742, 2.19792945])

In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("./Data/SalesJan2009.csv")

In [5]:
type(data)

pandas.core.frame.DataFrame