# Numpy 

In [2]:
import numpy as np

In [3]:
A = np.array([2,3,6,8])  ## np has a method called array which takes [numbers] and returns a object

In [4]:
print(A)

[2 3 6 8]


In [5]:
A*2

array([ 4,  6, 12, 16])

In [6]:
A**2

array([ 4,  9, 36, 64], dtype=int32)

In [7]:
np.sum(A)

19

In [8]:
np.median(A)

4.5

In [9]:
B = np.ones(4)
B

array([1., 1., 1., 1.])

In [10]:
C = np.arange(5)
C

array([0, 1, 2, 3, 4])

In [11]:
A = np.array([[2,3],[-1,-2]])
A

array([[ 2,  3],
       [-1, -2]])

In [12]:
B = np.array([[3,-1],[0,2]])
B

array([[ 3, -1],
       [ 0,  2]])

In [13]:
A*B

array([[ 6, -3],
       [ 0, -4]])

In [ ]:
A.dot(B)

In [16]:
sum(A.sum(axis=1))

2

In [17]:
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
A.ravel()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [24]:
np.random.seed(10)
np.random.randint(1,6,10)

array([2, 5, 1, 2, 4, 5, 2, 1, 2, 3])

In [26]:
np.random.uniform(60,100,10)

array([98.13573385, 60.15793065, 80.48769054, 92.50483847, 84.50104267,
       88.8702127 , 71.67504273, 96.7109649 , 88.58303134, 81.70177472])

In [27]:
np.random.normal(2,1,5)

array([1.64969879, 1.0103504 , 1.36574583, 3.89876222, 3.99652279])

# Pandas

In [30]:
import pandas as pd

In [32]:
data = pd.read_csv("./Data/SalesJan2009.csv")

In [33]:
data

Transaction_date   Product Price Payment_Type               Name  \
0    01-02-2009 06:17  Product1  1200   Mastercard           carolina   
1    01-02-2009 04:53  Product1  1200         Visa             Betina   
2    01-02-2009 13:08  Product1  1200   Mastercard  Federica e Andrea   
3    01-03-2009 14:44  Product1  1200         Visa              Gouya   
4    01-04-2009 12:56  Product2  3600         Visa            Gerd W    
5    01-04-2009 13:19  Product1  1200         Visa           LAURENCE   
6    01-04-2009 20:11  Product1  1200   Mastercard              Fleur   
7    01-02-2009 20:09  Product1  1200   Mastercard               adam   
8    01-04-2009 13:17  Product1  1200   Mastercard    Renee Elisabeth   
9    01-04-2009 14:11  Product1  1200         Visa              Aidan   
10   01-05-2009 02:42  Product1  1200       Diners              Stacy   
11   01-05-2009 05:39  Product1  1200         Amex              Heidi   
12   01-02-2009 09:16  Product1  1200   Mastercard              Sean    
13   01-05-2009 10:08  Product1  1200         Visa            Georgia   
14   01-02-2009 14:18  Product1  1200         Visa            Richard   
15   01-04-2009 01:05  Product1  1200       Diners             Leanne   
16   01-05-2009 11:37  Product1  1200         Visa              Janet   
17   01-06-2009 05:02  Product1  1200       Diners            barbara   
18   01-06-2009 07:45  Product2  3600         Visa             Sabine   
19   01-02-2009 07:35  Product1  1200       Diners               Hani   
20   01-06-2009 12:56  Product1  1200         Visa             Jeremy   
21   01-01-2009 11:05  Product1  1200       Diners              Janis   
22   01-05-2009 04:10  Product1  1200   Mastercard             Nicola   
23   01-06-2009 07:18  Product1  1200         Visa             asuman   
24   01-02-2009 01:11  Product1  1200   Mastercard               Lena   
25   01-01-2009 02:24  Product1  1200         Visa               Lisa   
26   01-07-2009 08:08  Product1  1200       Diners      Bryan Kerrene   
27   01-02-2009 02:57  Product1  1200         Visa              chris   
28   01-01-2009 20:21  Product1  1200         Visa             Maxine   
29   01-08-2009 00:42  Product1  1200         Visa             Family   
..                ...       ...   ...          ...                ...   
968  01-02-2009 17:24  Product2  3600       Diners              clara   
969  01-07-2009 18:15  Product1  1200   Mastercard              Selma   
970  01-03-2009 21:19  Product1  1200         Visa      Doug and Tina   
971  01-04-2009 05:13  Product1  1200         Visa             Lauren   
972  01-04-2009 09:28  Product1  1200         Visa                Jen   
973  01-02-2009 04:34  Product1  1200         Visa             gladys   
974     1/22/09 11:10  Product1  1200   Mastercard            Gustavo   
975  01-07-2009 12:06  Product1  1200         Visa              Erica   
976     1/29/09 13:25  Product1  1200       Diners               Hale   
977      1/27/09 2:57  Product1  1200         Visa           Rosemary   
978  01-07-2009 13:19  Product1  1200         Visa             Darian   
979     1/23/09 10:04  Product1  1200   Mastercard              Kevin   
980      1/19/09 4:55  Product1  1200         Visa             Alyssa   
981     1/28/09 22:02  Product1  1200         Visa               Hale   
982  01-04-2009 18:57  Product1  1200   Mastercard               KELI   
983  01-12-2009 20:31  Product1  1200         Visa               Glen   
984     1/24/09 12:00  Product1  1200         Visa                  T   
985     1/28/09 11:19  Product1  1200         Visa           christal   
986  01-07-2009 17:48  Product1  1200   Mastercard               Alex   
987     1/23/09 12:42  Product2  3600   Mastercard               Anke   
988  01-07-2009 19:48  Product2  3600   Mastercard             TRICIA   
989     1/26/09 11:19  Product1  1200   Mastercard              smith   
990  01-05-2009 13:23  Product1  1200         Visa             

In [34]:
data.head()

Transaction_date   Product Price Payment_Type               Name  \
0  01-02-2009 06:17  Product1  1200   Mastercard           carolina   
1  01-02-2009 04:53  Product1  1200         Visa             Betina   
2  01-02-2009 13:08  Product1  1200   Mastercard  Federica e Andrea   
3  01-03-2009 14:44  Product1  1200         Visa              Gouya   
4  01-04-2009 12:56  Product2  3600         Visa            Gerd W    

                           City     State         Country   Account_Created  \
0                      Basildon   England  United Kingdom  01-02-2009 06:00   
1  Parkville                           MO   United States  01-02-2009 04:42   
2  Astoria                             OR   United States  01-01-2009 16:21   
3                        Echuca  Victoria       Australia     9/25/05 21:13   
4  Cahaba Heights                      AL   United States    11/15/08 15:47   

         Last_Login   Latitude   Longitude  
0  01-02-2009 06:08  51.500000   -1.116667  
1  01-02-2009 07:49  39.195000  -94.681940  
2  01-03-2009 12:32  46.188060 -123.830000  
3  01-03-2009 14:22 -36.133333  144.750000  
4  01-04-2009 12:45  33.520560  -86.802500

In [35]:
type(data)

pandas.core.frame.DataFrame

In [36]:
data.shape

(998, 12)

In [39]:
data.columns

Index(['Transaction_date', 'Product', 'Price', 'Payment_Type', 'Name', 'City',
       'State', 'Country', 'Account_Created', 'Last_Login', 'Latitude',
       'Longitude'],
      dtype='object')

In [40]:
data["Name"]

0               carolina
1                 Betina
2      Federica e Andrea
3                  Gouya
4                Gerd W 
5               LAURENCE
6                  Fleur
7                   adam
8        Renee Elisabeth
9                  Aidan
10                 Stacy
11                 Heidi
12                 Sean 
13               Georgia
14               Richard
15                Leanne
16                 Janet
17               barbara
18                Sabine
19                  Hani
20                Jeremy
21                 Janis
22                Nicola
23                asuman
24                  Lena
25                  Lisa
26         Bryan Kerrene
27                 chris
28                Maxine
29                Family
             ...        
968                clara
969                Selma
970        Doug and Tina
971               Lauren
972                  Jen
973               gladys
974              Gustavo
975                Erica
976                 Hale


In [41]:
data["Country"]

0      United Kingdom
1       United States
2       United States
3           Australia
4       United States
5       United States
6       United States
7       United States
8              Israel
9              France
10      United States
11        Netherlands
12      United States
13      United States
14      United States
15            Ireland
16             Canada
17              India
18     United Kingdom
19      United States
20     United Kingdom
21            Ireland
22       South Africa
23      United States
24            Finland
25      United States
26      United States
27     United Kingdom
28      United States
29      United States
            ...      
968         Australia
969     United States
970     United States
971    Czech Republic
972    United Kingdom
973    United Kingdom
974           Romania
975             Malta
976     United States
977    United Kingdom
978            Turkey
979     United States
980    United Kingdom
981       New Zealand
982       

In [42]:
np.unique(data["Country"])

array(['Argentina', 'Australia', 'Austria', 'Bahrain', 'Belgium',
       'Bermuda', 'Brazil', 'Bulgaria', 'Canada', 'Cayman Isls', 'China',
       'Costa Rica', 'Czech Republic', 'Denmark', 'Dominican Republic',
       'Finland', 'France', 'Germany', 'Greece', 'Guatemala', 'Hong Kong',
       'Hungary', 'Iceland', 'India', 'Ireland', 'Israel', 'Italy',
       'Japan', 'Jersey', 'Kuwait', 'Latvia', 'Luxembourg', 'Malaysia',
       'Malta', 'Mauritius', 'Moldova', 'Monaco', 'Netherlands',
       'New Zealand', 'Norway', 'Philippines', 'Poland', 'Romania',
       'Russia', 'South Africa', 'South Korea', 'Spain', 'Sweden',
       'Switzerland', 'Thailand', 'The Bahamas', 'Turkey', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States'],
      dtype=object)

In [43]:
data.head()

Transaction_date   Product Price Payment_Type               Name  \
0  01-02-2009 06:17  Product1  1200   Mastercard           carolina   
1  01-02-2009 04:53  Product1  1200         Visa             Betina   
2  01-02-2009 13:08  Product1  1200   Mastercard  Federica e Andrea   
3  01-03-2009 14:44  Product1  1200         Visa              Gouya   
4  01-04-2009 12:56  Product2  3600         Visa            Gerd W    

                           City     State         Country   Account_Created  \
0                      Basildon   England  United Kingdom  01-02-2009 06:00   
1  Parkville                           MO   United States  01-02-2009 04:42   
2  Astoria                             OR   United States  01-01-2009 16:21   
3                        Echuca  Victoria       Australia     9/25/05 21:13   
4  Cahaba Heights                      AL   United States    11/15/08 15:47   

         Last_Login   Latitude   Longitude  
0  01-02-2009 06:08  51.500000   -1.116667  
1  01-02-2009 07:49  39.195000  -94.681940  
2  01-03-2009 12:32  46.188060 -123.830000  
3  01-03-2009 14:22 -36.133333  144.750000  
4  01-04-2009 12:45  33.520560  -86.802500

In [44]:
data.loc[1]

Transaction_date                01-02-2009 04:53
Product                                 Product1
Price                                       1200
Payment_Type                                Visa
Name                                      Betina
City                Parkville                   
State                                         MO
Country                            United States
Account_Created                 01-02-2009 04:42
Last_Login                      01-02-2009 07:49
Latitude                                  39.195
Longitude                               -94.6819
Name: 1, dtype: object

In [45]:
data.loc[2:5]

Transaction_date   Product Price Payment_Type               Name  \
2  01-02-2009 13:08  Product1  1200   Mastercard  Federica e Andrea   
3  01-03-2009 14:44  Product1  1200         Visa              Gouya   
4  01-04-2009 12:56  Product2  3600         Visa            Gerd W    
5  01-04-2009 13:19  Product1  1200         Visa           LAURENCE   

                           City     State        Country   Account_Created  \
2  Astoria                             OR  United States  01-01-2009 16:21   
3                        Echuca  Victoria      Australia     9/25/05 21:13   
4  Cahaba Heights                      AL  United States    11/15/08 15:47   
5  Mickleton                           NJ  United States     9/24/08 15:19   

         Last_Login   Latitude  Longitude  
2  01-03-2009 12:32  46.188060 -123.83000  
3  01-03-2009 14:22 -36.133333  144.75000  
4  01-04-2009 12:45  33.520560  -86.80250  
5  01-04-2009 13:04  39.790000  -75.23806

In [46]:
data.loc[2:5,["Name", "City"]]

Name                          City
2  Federica e Andrea  Astoria                     
3              Gouya                        Echuca
4            Gerd W   Cahaba Heights              
5           LAURENCE  Mickleton

In [47]:
data.loc[500:,["Name", "City"]]

Name                          City
500        Patrick  Birmingham                  
501          Heidi  St Augustine                
502            Tom  Salt Lake City              
503        Justine  Seattle                     
504         isabel                          Ruti
505          scott  Rogers                      
506         Fatima  Rogers                      
507           Judy                 Dun Laoghaire
508          Glenn                         Perth
509      Family in                        London
510         Lauren                         Gries
511        Michael              Pietermaritzburg
512           Jodi                Sutton Valence
513         simone                        Lyngby
514          Sonja  Alpine                      
515          Shane                        Zurich
516           Ruth                     Saskatoon
517           Cleo  Pacific Palisades           
518         Benoit              Fort Saint James
519         Claire                       Versoix
520         Claire  Trumansburg                 
521        Lindsey  Kennett Square              
522         Nicola  San Jose                    
523        PATRICK                Ban Khlong Sip
524       jennifer  Morro Bay                   
525            Amy                    Parramatta
526        Whitney                     Dumbleton
527         Astrid                   Altlengbach
528             jo                  Ballincollig
529       Michelle                  Ballincollig
..             ...                           ...
968          clara                         Perth
969          Selma  Greenville                  
970  Doug and Tina  Pls Vrds Est                
971         Lauren                Hradec Kralove
972            Jen                     Maidstone
973         gladys                  Saint Albans
974        Gustavo                     Voluntari
975          Erica                         Nadur
976           Hale  Morrison                    
977       Rosemary                        Cobham
978         Darian                         Izmir
979          Kevin  Hollywood                   
980         Alyssa                      Brighton
981           Hale                        Hawera
982           KELI                     Worongary
983           Glen                     Atlantida
984              T                   El Escorial
985       christal  Morrison                    
986           Alex  Augusta                     
987           Anke                        Avalon
988         TRICIA                        Sydney
989          smith                         Lahti
990           Macy                    Inner City
991       Lesleigh                         Baden
992         esther                  Huddersfield
993     Hans-Joerg                       Belfast
994     Christiane                   Black River
995         Pamela  Skaneateles                 
996          julie                     Haverhill
997         Julia   Madison                     

[498 rows x 2 columns]

In [112]:
set(("a","e","i"))

{'a', 'e', 'i'}

In [96]:
data.loc[:10,["Name", "City"]]

Name                          City
0            carolina                      Basildon
1              Betina  Parkville                   
2   Federica e Andrea  Astoria                     
3               Gouya                        Echuca
4             Gerd W   Cahaba Heights              
5            LAURENCE  Mickleton                   
6               Fleur  Peoria                      
7                adam  Martin                      
8     Renee Elisabeth                      Tel Aviv
9               Aidan                        Chatou
10              Stacy  New York

In [49]:
data

Transaction_date   Product Price Payment_Type               Name  \
0    01-02-2009 06:17  Product1  1200   Mastercard           carolina   
1    01-02-2009 04:53  Product1  1200         Visa             Betina   
2    01-02-2009 13:08  Product1  1200   Mastercard  Federica e Andrea   
3    01-03-2009 14:44  Product1  1200         Visa              Gouya   
4    01-04-2009 12:56  Product2  3600         Visa            Gerd W    
5    01-04-2009 13:19  Product1  1200         Visa           LAURENCE   
6    01-04-2009 20:11  Product1  1200   Mastercard              Fleur   
7    01-02-2009 20:09  Product1  1200   Mastercard               adam   
8    01-04-2009 13:17  Product1  1200   Mastercard    Renee Elisabeth   
9    01-04-2009 14:11  Product1  1200         Visa              Aidan   
10   01-05-2009 02:42  Product1  1200       Diners              Stacy   
11   01-05-2009 05:39  Product1  1200         Amex              Heidi   
12   01-02-2009 09:16  Product1  1200   Mastercard              Sean    
13   01-05-2009 10:08  Product1  1200         Visa            Georgia   
14   01-02-2009 14:18  Product1  1200         Visa            Richard   
15   01-04-2009 01:05  Product1  1200       Diners             Leanne   
16   01-05-2009 11:37  Product1  1200         Visa              Janet   
17   01-06-2009 05:02  Product1  1200       Diners            barbara   
18   01-06-2009 07:45  Product2  3600         Visa             Sabine   
19   01-02-2009 07:35  Product1  1200       Diners               Hani   
20   01-06-2009 12:56  Product1  1200         Visa             Jeremy   
21   01-01-2009 11:05  Product1  1200       Diners              Janis   
22   01-05-2009 04:10  Product1  1200   Mastercard             Nicola   
23   01-06-2009 07:18  Product1  1200         Visa             asuman   
24   01-02-2009 01:11  Product1  1200   Mastercard               Lena   
25   01-01-2009 02:24  Product1  1200         Visa               Lisa   
26   01-07-2009 08:08  Product1  1200       Diners      Bryan Kerrene   
27   01-02-2009 02:57  Product1  1200         Visa              chris   
28   01-01-2009 20:21  Product1  1200         Visa             Maxine   
29   01-08-2009 00:42  Product1  1200         Visa             Family   
..                ...       ...   ...          ...                ...   
968  01-02-2009 17:24  Product2  3600       Diners              clara   
969  01-07-2009 18:15  Product1  1200   Mastercard              Selma   
970  01-03-2009 21:19  Product1  1200         Visa      Doug and Tina   
971  01-04-2009 05:13  Product1  1200         Visa             Lauren   
972  01-04-2009 09:28  Product1  1200         Visa                Jen   
973  01-02-2009 04:34  Product1  1200         Visa             gladys   
974     1/22/09 11:10  Product1  1200   Mastercard            Gustavo   
975  01-07-2009 12:06  Product1  1200         Visa              Erica   
976     1/29/09 13:25  Product1  1200       Diners               Hale   
977      1/27/09 2:57  Product1  1200         Visa           Rosemary   
978  01-07-2009 13:19  Product1  1200         Visa             Darian   
979     1/23/09 10:04  Product1  1200   Mastercard              Kevin   
980      1/19/09 4:55  Product1  1200         Visa             Alyssa   
981     1/28/09 22:02  Product1  1200         Visa               Hale   
982  01-04-2009 18:57  Product1  1200   Mastercard               KELI   
983  01-12-2009 20:31  Product1  1200         Visa               Glen   
984     1/24/09 12:00  Product1  1200         Visa                  T   
985     1/28/09 11:19  Product1  1200         Visa           christal   
986  01-07-2009 17:48  Product1  1200   Mastercard               Alex   
987     1/23/09 12:42  Product2  3600   Mastercard               Anke   
988  01-07-2009 19:48  Product2  3600   Mastercard             TRICIA   
989     1/26/09 11:19  Product1  1200   Mastercard              smith   
990  01-05-2009 13:23  Product1  1200         Visa             

In [50]:
data_USA = data[data["Country"]=="United States"]

In [51]:
data_USA

Transaction_date   Product Price Payment_Type                  Name  \
1    01-02-2009 04:53  Product1  1200         Visa                Betina   
2    01-02-2009 13:08  Product1  1200   Mastercard     Federica e Andrea   
4    01-04-2009 12:56  Product2  3600         Visa               Gerd W    
5    01-04-2009 13:19  Product1  1200         Visa              LAURENCE   
6    01-04-2009 20:11  Product1  1200   Mastercard                 Fleur   
7    01-02-2009 20:09  Product1  1200   Mastercard                  adam   
10   01-05-2009 02:42  Product1  1200       Diners                 Stacy   
12   01-02-2009 09:16  Product1  1200   Mastercard                 Sean    
13   01-05-2009 10:08  Product1  1200         Visa               Georgia   
14   01-02-2009 14:18  Product1  1200         Visa               Richard   
19   01-02-2009 07:35  Product1  1200       Diners                  Hani   
23   01-06-2009 07:18  Product1  1200         Visa                asuman   
25   01-01-2009 02:24  Product1  1200         Visa                  Lisa   
26   01-07-2009 08:08  Product1  1200       Diners         Bryan Kerrene   
28   01-01-2009 20:21  Product1  1200         Visa                Maxine   
29   01-08-2009 00:42  Product1  1200         Visa                Family   
30   01-08-2009 03:56  Product1  1200   Mastercard             Katherine   
31   01-08-2009 03:16  Product1  1200   Mastercard                 Linda   
33   01-03-2009 09:03  Product1  1200       Diners                Sheila   
35   01-06-2009 07:46  Product1  1200         Amex                 Kelly   
37   01-08-2009 16:24  Product1  1200         Visa              jennifer   
38   01-09-2009 06:39  Product1  1200   Mastercard                Anneli   
39   01-06-2009 22:19  Product2  3600         Amex                  Ritz   
40   01-06-2009 23:00  Product2  3600         Amex                Sylvia   
41   01-07-2009 07:44  Product1  1200   Mastercard                 Marie   
43   01-07-2009 15:12  Product2  3600         Visa               Anabela   
44   01-07-2009 20:15  Product1  1200         Amex                Nicole   
45   01-03-2009 10:11  Product2  3600         Visa           Christiane    
48   01-10-2009 12:57  Product1  1200         Amex               Vanessa   
50   01-10-2009 12:05  Product1  1200         Visa                Karina   
..                ...       ...   ...          ...                   ...   
931      1/26/09 6:38  Product1  1200         Visa             Christian   
935      1/26/09 8:00  Product1  1200         Amex            Elizabeth    
936  01-11-2009 08:41  Product1  1200         Amex               Juliann   
937     1/21/09 10:32  Product1  1200   Mastercard                Julie    
940     1/31/09 18:12  Product1  1200         Visa               matthew   
941     1/22/09 15:35  Product1  1200         Visa                Steven   
942  01-05-2009 11:24  Product1  1200         Amex                 Angie   
943     1/23/09 11:23  Product1  1200   Mastercard                Lauren   
944  01-07-2009 20:55  Product1  1200   Mastercard                Esther   
945      1/13/09 9:40  Product1  1200         Visa             Elizabeth   
946     1/25/09 15:18  Product2  3600         Visa          marie-louise   
951      1/13/09 7:09  Product2  3600         Amex                  John   
952  01-03-2009 11:03  Product1  1200   Mastercard                 paula   
954  01-05-2009 07:55  Product1  1200   Mastercard              Isabelle   
955     1/25/09 14:40  Product1  1200         Visa               Maureen   
956     1/25/09 17:55  Product1  1200         Visa                 David   
957  01-03-2009 12:54  Product1  1200       Diners              caterina   
962  01-10-2009 09:32  Product2  3600   Mastercard                Cheryl   
963     1/22/09 12:45  Product3  7500         Visa  Frank and Christelle   
964  01-06-2009 18:11  Product2  3600   Mastercard                Triona   
966     1/25/09 10:50  Product1  1200       Diners   

In [52]:
data_anne = data[data["Name"]=="anne"]

In [53]:
data_anne

Transaction_date   Product Price Payment_Type  Name         City  \
100  01-08-2009 07:26  Product1  1200   Mastercard  anne  Bournemouth   

       State         Country Account_Created    Last_Login   Latitude  \
100  England  United Kingdom   1/25/08 15:46  1/15/09 1:36  50.716667   

     Longitude  
100  -1.883333

In [54]:
data_USA_Visa = data[(data["Country"]=="United States") & (data["Payment_Type"]=="Visa")]

In [55]:
data_USA_Visa.shape

(226, 12)

In [56]:
data["discount"] = 0.5

In [57]:
data

Transaction_date   Product Price Payment_Type               Name  \
0    01-02-2009 06:17  Product1  1200   Mastercard           carolina   
1    01-02-2009 04:53  Product1  1200         Visa             Betina   
2    01-02-2009 13:08  Product1  1200   Mastercard  Federica e Andrea   
3    01-03-2009 14:44  Product1  1200         Visa              Gouya   
4    01-04-2009 12:56  Product2  3600         Visa            Gerd W    
5    01-04-2009 13:19  Product1  1200         Visa           LAURENCE   
6    01-04-2009 20:11  Product1  1200   Mastercard              Fleur   
7    01-02-2009 20:09  Product1  1200   Mastercard               adam   
8    01-04-2009 13:17  Product1  1200   Mastercard    Renee Elisabeth   
9    01-04-2009 14:11  Product1  1200         Visa              Aidan   
10   01-05-2009 02:42  Product1  1200       Diners              Stacy   
11   01-05-2009 05:39  Product1  1200         Amex              Heidi   
12   01-02-2009 09:16  Product1  1200   Mastercard              Sean    
13   01-05-2009 10:08  Product1  1200         Visa            Georgia   
14   01-02-2009 14:18  Product1  1200         Visa            Richard   
15   01-04-2009 01:05  Product1  1200       Diners             Leanne   
16   01-05-2009 11:37  Product1  1200         Visa              Janet   
17   01-06-2009 05:02  Product1  1200       Diners            barbara   
18   01-06-2009 07:45  Product2  3600         Visa             Sabine   
19   01-02-2009 07:35  Product1  1200       Diners               Hani   
20   01-06-2009 12:56  Product1  1200         Visa             Jeremy   
21   01-01-2009 11:05  Product1  1200       Diners              Janis   
22   01-05-2009 04:10  Product1  1200   Mastercard             Nicola   
23   01-06-2009 07:18  Product1  1200         Visa             asuman   
24   01-02-2009 01:11  Product1  1200   Mastercard               Lena   
25   01-01-2009 02:24  Product1  1200         Visa               Lisa   
26   01-07-2009 08:08  Product1  1200       Diners      Bryan Kerrene   
27   01-02-2009 02:57  Product1  1200         Visa              chris   
28   01-01-2009 20:21  Product1  1200         Visa             Maxine   
29   01-08-2009 00:42  Product1  1200         Visa             Family   
..                ...       ...   ...          ...                ...   
968  01-02-2009 17:24  Product2  3600       Diners              clara   
969  01-07-2009 18:15  Product1  1200   Mastercard              Selma   
970  01-03-2009 21:19  Product1  1200         Visa      Doug and Tina   
971  01-04-2009 05:13  Product1  1200         Visa             Lauren   
972  01-04-2009 09:28  Product1  1200         Visa                Jen   
973  01-02-2009 04:34  Product1  1200         Visa             gladys   
974     1/22/09 11:10  Product1  1200   Mastercard            Gustavo   
975  01-07-2009 12:06  Product1  1200         Visa              Erica   
976     1/29/09 13:25  Product1  1200       Diners               Hale   
977      1/27/09 2:57  Product1  1200         Visa           Rosemary   
978  01-07-2009 13:19  Product1  1200         Visa             Darian   
979     1/23/09 10:04  Product1  1200   Mastercard              Kevin   
980      1/19/09 4:55  Product1  1200         Visa             Alyssa   
981     1/28/09 22:02  Product1  1200         Visa               Hale   
982  01-04-2009 18:57  Product1  1200   Mastercard               KELI   
983  01-12-2009 20:31  Product1  1200         Visa               Glen   
984     1/24/09 12:00  Product1  1200         Visa                  T   
985     1/28/09 11:19  Product1  1200         Visa           christal   
986  01-07-2009 17:48  Product1  1200   Mastercard               Alex   
987     1/23/09 12:42  Product2  3600   Mastercard               Anke   
988  01-07-2009 19:48  Product2  3600   Mastercard             TRICIA   
989     1/26/09 11:19  Product1  1200   Mastercard              smith   
990  01-05-2009 13:23  Product1  1200         Visa             

In [ ]:
data["New_price"] = data["Price"]*data["discount"]

In [ ]:
def convert (a):
    return float(a)

In [ ]:
data["Price"].apply(convert)

In [63]:
A ="10,000"

In [67]:
float(A.replace(",",""))

10000.0

In [ ]:
A = "13,000"
float(A)

In [ ]:
A = A.replace(",","")

In [ ]:
float(A)

In [69]:
def convert (a):
    c =a.replace(",","")
    return float(c)

In [70]:
data["Price"] = data["Price"].apply(convert)

In [ ]:
data["Price"] = data["Price"].apply(lambda x: float(x = x.replace(",","")))

In [71]:
data["New_price"] = data["Price"]*data["discount"]

In [72]:
data

Transaction_date   Product   Price Payment_Type               Name  \
0    01-02-2009 06:17  Product1  1200.0   Mastercard           carolina   
1    01-02-2009 04:53  Product1  1200.0         Visa             Betina   
2    01-02-2009 13:08  Product1  1200.0   Mastercard  Federica e Andrea   
3    01-03-2009 14:44  Product1  1200.0         Visa              Gouya   
4    01-04-2009 12:56  Product2  3600.0         Visa            Gerd W    
5    01-04-2009 13:19  Product1  1200.0         Visa           LAURENCE   
6    01-04-2009 20:11  Product1  1200.0   Mastercard              Fleur   
7    01-02-2009 20:09  Product1  1200.0   Mastercard               adam   
8    01-04-2009 13:17  Product1  1200.0   Mastercard    Renee Elisabeth   
9    01-04-2009 14:11  Product1  1200.0         Visa              Aidan   
10   01-05-2009 02:42  Product1  1200.0       Diners              Stacy   
11   01-05-2009 05:39  Product1  1200.0         Amex              Heidi   
12   01-02-2009 09:16  Product1  1200.0   Mastercard              Sean    
13   01-05-2009 10:08  Product1  1200.0         Visa            Georgia   
14   01-02-2009 14:18  Product1  1200.0         Visa            Richard   
15   01-04-2009 01:05  Product1  1200.0       Diners             Leanne   
16   01-05-2009 11:37  Product1  1200.0         Visa              Janet   
17   01-06-2009 05:02  Product1  1200.0       Diners            barbara   
18   01-06-2009 07:45  Product2  3600.0         Visa             Sabine   
19   01-02-2009 07:35  Product1  1200.0       Diners               Hani   
20   01-06-2009 12:56  Product1  1200.0         Visa             Jeremy   
21   01-01-2009 11:05  Product1  1200.0       Diners              Janis   
22   01-05-2009 04:10  Product1  1200.0   Mastercard             Nicola   
23   01-06-2009 07:18  Product1  1200.0         Visa             asuman   
24   01-02-2009 01:11  Product1  1200.0   Mastercard               Lena   
25   01-01-2009 02:24  Product1  1200.0         Visa               Lisa   
26   01-07-2009 08:08  Product1  1200.0       Diners      Bryan Kerrene   
27   01-02-2009 02:57  Product1  1200.0         Visa              chris   
28   01-01-2009 20:21  Product1  1200.0         Visa             Maxine   
29   01-08-2009 00:42  Product1  1200.0         Visa             Family   
..                ...       ...     ...          ...                ...   
968  01-02-2009 17:24  Product2  3600.0       Diners              clara   
969  01-07-2009 18:15  Product1  1200.0   Mastercard              Selma   
970  01-03-2009 21:19  Product1  1200.0         Visa      Doug and Tina   
971  01-04-2009 05:13  Product1  1200.0         Visa             Lauren   
972  01-04-2009 09:28  Product1  1200.0         Visa                Jen   
973  01-02-2009 04:34  Product1  1200.0         Visa             gladys   
974     1/22/09 11:10  Product1  1200.0   Mastercard            Gustavo   
975  01-07-2009 12:06  Product1  1200.0         Visa              Erica   
976     1/29/09 13:25  Product1  1200.0       Diners               Hale   
977      1/27/09 2:57  Product1  1200.0         Visa           Rosemary   
978  01-07-2009 13:19  Product1  1200.0         Visa             Darian   
979     1/23/09 10:04  Product1  1200.0   Mastercard              Kevin   
980      1/19/09 4:55  Product1  1200.0         Visa             Alyssa   
981     1/28/09 22:02  Product1  1200.0         Visa               Hale   
982  01-04-2009 18:57  Product1  1200.0   Mastercard               KELI   
983  01-12-2009 20:31  Product1  1200.0         Visa               Glen   
984     1/24/09 12:00  Product1  1200.0         Visa                  T   
985     1/28/09 11:19  Product1  1200.0         Visa           christal   
986  01-07-2009 17:48  Product1  1200.0   Mastercard               Alex   
987     1/23/09 12:42  Product2  3600.0   Mastercard               Anke   
988  01-07-2009 19:48  Product2  3600.0   Mastercard             TRICIA   
989     1/26/09 11:19  Product

In [73]:
data = data.drop(["Last_Login"],axis=1)

In [74]:
data_1 = data.loc[:,["Transaction_date","Product","Price","Payment_Type", "Name","Account_Created"]]

In [79]:
data_1.to_csv("data_subset_1.csv")

In [77]:
data_2 = data.drop(["Transaction_date","Product","Price","Payment_Type", "Name","Account_Created"],axis=1)

In [78]:
data_2.to_csv("data_subset_2.csv")

In [80]:
d1 = {'Customer_id':np.array([1,2,3,4,5,6]),
  'Product':np.array(['Oven','Oven','Oven','Television','Television','Television'])}


In [82]:
df1 = pd.DataFrame(d1)

In [83]:
df1

Customer_id     Product
0            1        Oven
1            2        Oven
2            3        Oven
3            4  Television
4            5  Television
5            6  Television

In [84]:
d2 = {'Customer_id':np.array([2,4,6,10]),
    'State':np.array(['California','California','Texas','Boston'])}
df2 = pd.DataFrame(d2)

In [85]:
df2

Customer_id       State
0            2  California
1            4  California
2            6       Texas
3           10      Boston

In [86]:
inner_join = pd.merge(df1,df2, on = "Customer_id",how= "inner")

In [88]:
left_join = pd.merge(df1,df2, on = "Customer_id",how= "left")

In [89]:
left_join

Customer_id     Product       State
0            1        Oven         NaN
1            2        Oven  California
2            3        Oven         NaN
3            4  Television  California
4            5  Television         NaN
5            6  Television       Texas

In [90]:
right_join = pd.merge(df1,df2, on = "Customer_id",how= "right")

In [91]:
right_join

Customer_id     Product       State
0            2        Oven  California
1            4  Television  California
2            6  Television       Texas
3           10         NaN      Boston

In [92]:
outer_join = pd.merge(df1,df2, on = "Customer_id",how= "outer")

In [93]:
outer_join

Customer_id     Product       State
0            1        Oven         NaN
1            2        Oven  California
2            3        Oven         NaN
3            4  Television  California
4            5  Television         NaN
5            6  Television       Texas
6           10         NaN      Boston

In [94]:
outer_join = outer_join.fillna(0)

In [95]:
outer_join

Customer_id     Product       State
0            1        Oven           0
1            2        Oven  California
2            3        Oven           0
3            4  Television  California
4            5  Television           0
5            6  Television       Texas
6           10           0      Boston